# Generated by Django 5.0.4 on 2024-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
                ('CourseName', models.CharField(max_length=200)),
                ('Fees', models.IntegerField()),
            ],
        ),
    ]
